# Generated by Django 2.0.5 on 2018-07-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('attribute', models.CharField(db_column='attribute', default='all', max_length=50)),
                ('difficulty', models.CharField(db_column='difficulty', max_length=50)),
                ('level', models.IntegerField(db_column='level')),
                ('artist', models.CharField(db_column='artist', max_length=100)),
                ('style', models.CharField(db_column='style', default='5', max_length=50)),
                ('limited', models.CharField(blank=True, db_column='limited', default=None, max_length=50, null=True)),
                ('party', models.BooleanField(db_column='party', default=False)),
            ],
            options={
                'db_table': 'song_list',
            },
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('title', 'difficulty', 'attribute')},
        ),
    ]
