# Generated by Django 2.0.5 on 2018-08-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_column='path', max_length=200)),
                ('kind', models.CharField(db_column='name', max_length=100)),
                ('serial', models.IntegerField(db_column='serial')),
                ('person', models.CharField(db_column='person', max_length=100)),
                ('year', models.IntegerField(db_column='year')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
    ]
