# Generated by Django 2.0.5 on 2019-01-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photo',
            table='old_photo',
        ),
    ]
