# Generated by Django 2.0.5 on 2019-01-19 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Albam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateField(db_column='created_at', default=django.utils.timezone.now),
        ),
    ]
