# Generated by Django 2.0.5 on 2019-01-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Albam', '0002_auto_20190120_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(db_column='photo', upload_to='Albam/images/'),
        ),
    ]
