# Generated by Django 2.0.5 on 2019-01-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Albam', '0003_auto_20190122_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(db_column='photo', upload_to='images/Albam/'),
        ),
    ]
