# Generated by Django 2.0.5 on 2019-02-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Albam', '0005_auto_20190204_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='albam',
            name='btn_class',
            field=models.CharField(db_column='btn_class', default='kaoru', max_length=100),
            preserve_default=False,
        ),
    ]
