# Generated by Django 2.1.7 on 2019-03-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Albam', '0006_albam_btn_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='twitter_account',
            field=models.CharField(db_column='account', default=None, max_length=250),
        ),
    ]
