# Generated by Django 2.1.7 on 2019-03-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Albam', '0009_auto_20190331_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='comment',
            field=models.TextField(db_column='comment', default=None),
            preserve_default=False,
        ),
    ]
