# Generated by Django 2.1.7 on 2019-03-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Albam', '0011_auto_20190331_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='albam',
            name='order_rule',
            field=models.BooleanField(db_column='order_rule', default=False),
        ),
    ]
