# Generated by Django 2.1.7 on 2019-03-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Albam', '0012_albam_order_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='albam',
            name='jumbotron_image',
            field=models.CharField(blank=True, db_column='jumbotron', default=None, max_length=240, null=True),
        ),
    ]
