# Generated by Django 2.1.7 on 2019-03-31 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Albam', '0013_albam_jumbotron_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albam',
            name='jumbotron_image',
            field=models.ForeignKey(blank=True, db_column='jumbotron', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Albam.Picture'),
        ),
    ]
