# Generated by Django 2.1.8 on 2019-04-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Albam', '0014_auto_20190331_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='twitter_account',
            field=models.BigIntegerField(blank=True, db_column='account', default=None, null=True),
        ),
    ]
